---

- name: Install required APT packages
  package:
    name: '{{ q("flattened", haproxy__base_packages
                             + haproxy__packages) }}'
    state: 'present'
  register: haproxy__register_packages
  until: haproxy__register_packages is succeeded
  notify: [ 'Restart haproxy' ]

- name: Divert the original haproxy configuration file
  command: dpkg-divert --quiet --local --divert /etc/haproxy/haproxy.cfg.dpkg-divert --rename /etc/haproxy/haproxy.cfg
  args:
    creates: '/etc/haproxy/haproxy.cfg.dpkg-divert'

- name: Generate haproxy configuration
  template:
    src: '{{ lookup("template_src", "haproxy/haproxy.cfg.j2") }}'
    dest: '/etc/haproxy/haproxy.cfg'
    mode: '0644'
  notify: [ 'Restart haproxy' ]

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    mode: '0755'

- name: Save haproxy local facts
  template:
    src: 'etc/ansible/facts.d/haproxy.fact.j2'
    dest: '/etc/ansible/facts.d/haproxy.fact'
    mode: '0755'
  register: haproxy__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: haproxy__register_facts is changed
